select_origin: directory
files_origin: ./fiches
nodes_origin: ""
links_origin: ""
nodes_online: ""
links_online: ""
images_origin: ""
export_target: ""
history: true
focus_max: 2
record_types:
  undefined:
    fill: "#858585"
    stroke: "#858585"
  Pagès:
    fill: "#a6cee3"
    stroke: "#a6cee3"
  Collègue:
    fill: "#1f78b4"
    stroke: "#1f78b4"
  Collaborateur:
    fill: "#b2df8a"
    stroke: "#b2df8a"
  Famille:
    fill: "#33a02c"
    stroke: "#33a02c"
  Opposant:
    fill: "#fb9a99"
    stroke: "#fb9a99"
  Influenceur:
    fill: "#6495ED"
    stroke: "#6495ED"
  Organisation:
    fill: "#fdbf6f"
    stroke: "#fdbf6f"
  Objet:
    fill: "#ff7f00"
    stroke: "#ff7f00"
  Psychologie:
    fill: "#cab2d6"
    stroke: "#cab2d6"
  Sciences de l'information et de la communication:
    fill: "#6a3d9a"
    stroke: "#6a3d9a"
  Philosophie:
    fill: "#ffff99"
    stroke: "#ffff99"
  Sociologie:
    fill: "#b15928"
    stroke: "#b15928"
  Psychiatrie:
    fill: "#fbb4ae"
    stroke: "#fbb4ae"
  Sciences de l'éducation:
    fill: "#b3cde3"
    stroke: "#b3cde3"
  Transdisciplinaire:
    fill: "#ccebc5"
    stroke: "#ccebc5"
  Concept:
    fill: "#f2a5d0"
    stroke: "#f2a5d0"
link_types:
  undefined:
    stroke: simple
    color: "#c2c2c2"
  i:
    stroke: simple
    color: "#6495ED"
  d:
    stroke: simple
    color: "#50C878"
  o:
    stroke: dash
    color: "#FF4500"
record_filters: []
graph_background_color: "#ffffff"
graph_highlight_color: "#ff6a6a"
graph_highlight_on_hover: true
graph_text_size: 11
graph_arrows: true
node_size_method: degree
node_size: 10
node_size_max: 20
node_size_min: 2
attraction_force: 220
attraction_distance_max: 240
attraction_vertical: 0
attraction_horizontal: 0
views: {}
chronological_record_meta: created
record_metas:
  - Prénom
  - Nom
  - Genre
  - Pays
  - Naissance
  - Décès
  - idref
title: Pagèsosphère
author: Olivier Le Deuff
description: Le réseau de Robert Pagès
keywords: []
link_symbol: ☞
csl: ./apa-fr.csl
bibliography: ./bibliorobert.json
csl_locale: locales.xml
css_custom: "./pages.css"
devtools: false
lang: fr
name: ""
